from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from datetime import datetime

from .models import Student
from .forms import StudentForm


def dashboard(request):

    total_students = Student.objects.count()

    context = {
        'total_students': total_students,
        'total_courses': 6,
        'total_departments': 4,
        'total_reports': 12,
        'current_date': datetime.now(),
    }

    return render(request, 'dashboard.html', context)


def student_list(request):

    search = request.GET.get('search')

    if search:

        student_list = Student.objects.filter(
            full_name__icontains=search
        )

    else:

        student_list = Student.objects.all()

    paginator = Paginator(student_list, 5)

    page_number = request.GET.get('page')

    students = paginator.get_page(page_number)

    return render(
        request,
        'student_list.html',
        {'students': students}
    )
def export_students_pdf(request):

    response = HttpResponse(
        content_type='application/pdf'
    )

    response['Content-Disposition'] = (
        'attachment; filename="students_report.pdf"'
    )

    pdf = canvas.Canvas(response)

    width, height = 595, 842

    # Title
    pdf.setFont("Helvetica-Bold", 24)

    pdf.drawString(
        180,
        800,
        "Student Report"
    )

    # Line
    pdf.line(50, 770, 545, 770)

    # Table Headers
    pdf.setFont("Helvetica-Bold", 13)

    y = 720

    pdf.drawString(60, y, "ID")
    pdf.drawString(110, y, "Name")
    pdf.drawString(300, y, "Roll No")
    pdf.drawString(400, y, "Department")

    # Students
    students = Student.objects.all()

    y -= 30

    pdf.setFont("Helvetica", 12)

    for student in students:

        pdf.drawString(
            60,
            y,
            str(student.id)
        )

        pdf.drawString(
            110,
            y,
            student.full_name
        )

        pdf.drawString(
            300,
            y,
            str(student.roll_number)
        )

        pdf.drawString(
            400,
            y,
            student.department
        )

        y -= 28

    # Footer
    pdf.line(50, 80, 545, 80)

    pdf.setFont("Helvetica-Oblique", 10)

    pdf.drawString(
        190,
        60,
        "Generated by Student Management System"
    )

    pdf.save()

    return response

def add_student(request):

    if request.method == 'POST':

        form = StudentForm(
            request.POST,
            request.FILES
        )

        if form.is_valid():

            form.save()

            return redirect('student_list')

    else:

        form = StudentForm()

    return render(
        request,
        'add_student.html',
        {'form': form}
    )


def student_detail(request, id):

    student = get_object_or_404(
        Student,
        id=id
    )

    return render(
        request,
        'student_detail.html',
        {'student': student}
    )


def delete_student(request, id):

    student = get_object_or_404(
        Student,
        id=id
    )

    student.delete()

    return redirect('student_list')


def about(request):

    return render(
        request,
        'about.html'
    )


def edit_student(request, id):

    student = Student.objects.get(id=id)

    if request.method == 'POST':

        student.full_name = request.POST.get('full_name')
        student.roll_number = request.POST.get('roll_number')
        student.email = request.POST.get('email')
        student.phone = request.POST.get('phone')
        student.department = request.POST.get('department')
        student.course = request.POST.get('course')
        student.year = request.POST.get('year')
        student.date_of_birth = request.POST.get('date_of_birth')

        if request.FILES.get('photo'):

            student.photo = request.FILES.get('photo')

        student.save()

        return redirect('/students/')

    return render(
        request,
        'edit_student.html',
        {'student': student}
    )


def login_view(request):

    if request.user.is_authenticated:

        return redirect('/')

    error = ''

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:

            login(request, user)

            return redirect('/')

        else:

            error = 'Username or Password Incorrect'

    return render(
        request,
        'login.html',
        {'error': error}
    )


def logout_view(request):

    logout(request)

    return redirect('/login/')